version: 2

build:
  os: "ubuntu-22.04"
  python:
    version: 3.8
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --with docs

sphinx:
  configuration: docs/conf.py