name: uv/ci

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "__pycache__"
      - ".pytest_cache"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: CI/CD Build & Test w/pytest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        astropy-version: ["6.1.7", "7.0"]
        exclude:
          - python-version: "3.10"
            astropy-version: "7.0"

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --frozen --group dev

      - name: Pin astropy version
        run: uv pip install "astropy==${{ matrix.astropy-version }}.*"

      - name: Run tests
        run: uv run pytest
